### ISSUE TITLE
composer reports facebook/php-sdk-v4 is abandoned

### ISSUE THREAD

**Issue by rmohns** [imarc/padstone#6]
@khamer creating a new project from padstone, noticed this in the output:

`Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.`

**Comment by ghost** [comment]
I'm fairly certain this is coming from the Imarc Social plugin (which is included in padstone). We should update Social before pulling it in. @rmohns if you arent using the plugin you can disable or uninstall it in Settings > Plugins to avoid any potential issues.
